### PR TITLE
Fixing The QUIT\n\rQUIT bug

### PR DESCRIPTION
**Pull request by miawgogo**

### CODE REVIEW

**Comment by miawgogo** [comment]
Developer(Gamah) has own way of implementation in head, but not in code

**Comment by Gamah** [comment]
There's probably some usable code here, I'd like to have the PR open for the next time I'm interested in working on this project.

**Comment by miawgogo** [comment]
closing pull due to repo inactivty, send message for patch file

**Comment by Gamah** [comment]
Reopening again for reference when I work on the project next...

**Pull request closed without merging**
